# Generated by Django 3.2.8 on 2021-11-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, null=True)),
                ('firstName', models.CharField(max_length=80, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
