# Generated by Django 3.2.8 on 2021-11-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('utilisateurs', '0001_initial'),
        ('rendezVous', '0002_rendezvous_createurid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='createurId',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='createur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='utilisateurs.utilisateur'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='lieu',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='sports.sport'),
        ),
    ]
